### ISSUE TITLE
.publishJob error doesn't get caught in catch block

### ISSUE THREAD

**Issue by coockoo** [titarenko/mqu#1]
Code sample to reproduce

```javascript
// I intentionally changed port 5672 -> 5673 to get an error
const mqu = require('mqu')('amqp://guest:guest@localhost:5673')

async function main () {
	try {
		await mqu.publishJob('job', { kappa: 'lul' })
	} catch (error) {
		// Doesn't catch
		console.error('Caught', error)
	}
}

main()

// Doesn't catch
process.on('unhandledRejection', (error) => console.error('Unhandled', error))
// Caught here :thinking_face:
process.on('uncaughtException', (error) => console.error('Uncaught', error))
```

**Comment by titarenko** [comment]
Hi!

As shown in example (README.md):

```js
const mqu = require('mqu')('amqp://guest:guest@localhost:5672')

mqu.on('error', error => {
  console.error('oh my, error!!', error)
  process.kill(process.pid)
})
```

That error you mention is socket error, so it's related to connection (transport level), not to amqp protocol method invocation (application level). That's why such errors go on 'basic' API level, which is responsible for establishing connection.

**Comment by titarenko** [comment]
Also, if you wonder why you've observed error here:

```
// Caught here :thinking_face:
process.on('uncaughtException', (error) => console.error('Uncaught', error))
```

Thats is default behavior of node runtime: if you do not have listener of 'error' event on any EventEmitter instance, that error would be thrown. And since it wouldn't be caught, it will become an uncaughtException.

**Comment by coockoo** [comment]
Thank you for the explanation! I was confused by the fact that `.publishJob` returns Promise so I expected it to act like a Promise in error handling.
